/*This is a car sales platform database. It is composed of the following tables and columns:
  CITY: ID, CITY
  TOWN: ID, CITYID, TOWN
  DISTRICT: ID, TOWNID, DISTRICT
  USER_: ID, USERNAME_, PASSWORD_, NAMESURNAME, EMAIL, GENDER, CREATEDDATE, BIRTHDATE, TELNR1, TELNR2, CITYID, TOWNID, DISTRICTID
  WEBOFFERS: ID, USERID, CITYID, TOWNID, DISTRICTID, TITLE, BRAND, MODEL, PRICE, YEAR_, KM, FUEL, SHIFTTYPE, MOTORVOLUME, MOTORPOWER,
COLOR, CASETYPE, FROMWHO, VARYANT, ORIGINALID, TELNR, DATE_ */

-- Number and percentage of vehicles for each brand
SELECT BRAND, COUNT(*) VEHICLECOUNT, ROUND(CONVERT(FLOAT,COUNT(*))*100/(SELECT COUNT(*) FROM WEBOFFERS),2) PERCENTAGE_
FROM WEBOFFERS
GROUP BY BRAND
ORDER BY 2 DESC

-- Number of vehicles in each city
SELECT C.CITY, COUNT(*) VEHICLE_COUNT FROM WEBOFFERS W
JOIN CITY C ON C.ID = W.CITYID
GROUP BY CITY
ORDER BY VEHICLE_COUNT DESC

SELECT CITY,
(SELECT COUNT(*) FROM WEBOFFERS WHERE CITYID = C.ID) VEHICLE_COUNT
FROM CITY C
ORDER BY 2 DESC

-- Volkswagen Passat records in Istanbul, from owner, 2014-2018 model, automatic transmission, diesel
SELECT U.USERNAME_, C.CITY, T.TOWN, D.DISTRICT, W.TITLE, W.BRAND, W.MODEL, W.PRICE, W.YEAR_, W.KM, W.FUEL, W.SHIFTTYPE, W.COLOR,
W.VARYANT FROM WEBOFFERS W 
JOIN CITY C ON C.ID = W.CITYID
JOIN TOWN T ON T.ID = W.TOWNID 
JOIN DISTRICT D ON D.ID = W.DISTRICTID
JOIN USER_ U ON U.ID = W.USERID
WHERE CITY = 'ÝSTANBUL' AND MODEL = 'Passat' AND FROMWHO = 'Sahibinden' AND YEAR_ BETWEEN 2014 AND 2018
AND SHIFTTYPE IN ('Yarý Otomatik Vites', 'Otomatik Vites') AND FUEL = 'Dizel'
ORDER BY KM, PRICE

-- BMW vehicles in Istanbul, Ankara and Izmir
SELECT U.USERNAME_, C.CITY, T.TOWN, D.DISTRICT, W.TITLE, W.BRAND, W.MODEL, W.PRICE, W.YEAR_, W.KM, W.FUEL, W.SHIFTTYPE, W.COLOR,
W.VARYANT FROM WEBOFFERS W 
JOIN CITY C ON C.ID = W.CITYID
JOIN TOWN T ON T.ID = W.TOWNID 
JOIN DISTRICT D ON D.ID = W.DISTRICTID
JOIN USER_ U ON U.ID = W.USERID
WHERE W.BRAND = 'BMW' 
AND C.CITY IN (SELECT VALUE FROM string_split('ANKARA,ÝSTANBUL,ÝZMÝR', ','))
