-- This is an e-trade database. It contains these tables and columns:
-- ADDRESS: ID, USERID, COUNTRYID, CITYID, TOWNID, DISTRICTID, POSTALCODE, ADDRESSTEXT
-- CITIES: ID, COUNTRYID, CITY
-- COUNTRIES: ID, COUNTRY
-- DISTRICTS: ID, TOWNID, DISTRICT
-- INVOICEDETAILS: ID, INVOICEID, ORDERDETAILID, ITEMID, AMOUNT, UNITPRICE, LINETOTAL
-- INVOICES: ID, ORDERID, DATE_, ADDRESSID, CARGOFICHENO, TOTALPRICE
-- ITEMS: ID, ITEMCODE, ITEMNAME, UNITPRICE, CATEGORY1, CATEGORY2, CATEGORY3, CATEGORY4, BRAND
-- ORDERDETAILS: ID, ORDERID, ITEMID, AMOUNT, UNITPRICE, LINETOTAL
-- ORDERS: ID, USERID, DATE_, TOTALPRICE, STATUS_, ADDRESSID
-- SALEORDERS: ID, USERNAME_, NAMESURNAME, TELNR1, TELNR2, COUNTRY, CITY, TOWN, ADDRESSTEXT, ORDERID, ITEMCODE, ITEMNAME, BRAND, CATEGORY1,
--		CATEGORY2, CATEGORY3, CATEGORY4, AMOUNT, UNITPRICE, LINETOTAL, ORDERDATE, ORDERTIME, YEAR_, MONTH_, DAYOFWEEK_
-- TOWNS: ID, CITYID, TOWN
-- USERS: ID, USERNAME_, PASSWORD_, NAMESURNAME, EMAIL, GENDER, BIRTHDATE, CREATEDDATE, TELNR1, TELNR2


-- Sum of sales by city
SELECT CITY, SUM(LINETOTAL) TOTALSALES FROM SALEORDERS
GROUP BY CITY
ORDER BY 2 DESC

-- Sum of sales per month by city
SELECT CITY, MONTH_, SUM(LINETOTAL) TOTALSALES FROM SALEORDERS
GROUP BY CITY, MONTH_
ORDER BY CITY, MONTH_
 
-- Sum of sales per day of week by city
SELECT CITY, DAYOFWEEK_, SUM(LINETOTAL) TOTALSALES FROM SALEORDERS
GROUP BY CITY, DAYOFWEEK_
ORDER BY CITY, DAYOFWEEK_

-- Sum of sales per day of week by city, days in columns
SELECT DISTINCT(CITY), 
(SELECT SUM(LINETOTAL) FROM SALEORDERS WHERE CITY = S.CITY AND DAYOFWEEK_='01.PZT') MONDAY,
(SELECT SUM(LINETOTAL) FROM SALEORDERS WHERE CITY = S.CITY AND DAYOFWEEK_='02.SAL') TUESDAY,
(SELECT SUM(LINETOTAL) FROM SALEORDERS WHERE CITY = S.CITY AND DAYOFWEEK_='03.ÇAR') WEDNESDAY,
(SELECT SUM(LINETOTAL) FROM SALEORDERS WHERE CITY = S.CITY AND DAYOFWEEK_='04.PER') THURSDAY,
(SELECT SUM(LINETOTAL) FROM SALEORDERS WHERE CITY = S.CITY AND DAYOFWEEK_='05.CUM') FRIDAY,
(SELECT SUM(LINETOTAL) FROM SALEORDERS WHERE CITY = S.CITY AND DAYOFWEEK_='06.CMT') SATURDAY,
(SELECT SUM(LINETOTAL) FROM SALEORDERS WHERE CITY = S.CITY AND DAYOFWEEK_='07.PAZ') SUNDAY
FROM SALEORDERS S
ORDER BY 1 

-- Top 5 categories of each city
SELECT DISTINCT S.CITY, S1.CATEGORY1, S1.TOTALSALE TOTALSALE
FROM SALEORDERS S
CROSS APPLY(SELECT TOP 5 CATEGORY1, SUM(LINETOTAL) TOTALSALE FROM SALEORDERS WHERE CITY = S.CITY GROUP BY CATEGORY1 ORDER BY 2 DESC) S1
ORDER BY CITY, S1.TOTALSALE DESC

-- Top 3 categories and top 3 subcategories of these categories of each city
SELECT DISTINCT CITY, S1.CATEGORY1, S2.CATEGORY2, S2.TOTALSALE 
FROM SALEORDERS S
CROSS APPLY(SELECT TOP 3 CATEGORY1, SUM(LINETOTAL) TOTALSALE FROM SALEORDERS WHERE CITY = S.CITY GROUP BY CATEGORY1 ORDER BY 2 DESC) S1
CROSS APPLY(SELECT TOP 3 CATEGORY2, SUM(LINETOTAL) TOTALSALE FROM SALEORDERS WHERE CITY = S.CITY AND CATEGORY1 = S1.CATEGORY1 GROUP BY CATEGORY2 ORDER BY 2 DESC) S2
ORDER BY 1,2,4 DESC

-- Total sale by each city, using relational tables
SELECT C.CITY, SUM(O.TOTALPRICE) TOTALSALE FROM ORDERS O
JOIN ADDRESS A ON A.ID = O.ADDRESSID
JOIN CITIES C ON C.ID = A.CITYID
GROUP BY C.CITY

SELECT CITY,
(SELECT SUM(TOTALPRICE) FROM ORDERS WHERE ADDRESSID IN
(SELECT ID FROM ADDRESS WHERE CITYID = C.ID)) TOTALSALE
FROM CITIES C

-- Categories of each brand
SELECT I.BRAND, I.CATEGORY1, SUM(OD.LINETOTAL) TOTALPRICE FROM ORDERDETAILS OD
JOIN ITEMS I ON I.ID = OD.ITEMID
GROUP BY I.BRAND, I.CATEGORY1
ORDER BY BRAND, TOTALPRICE DESC

SELECT I.BRAND, I.CATEGORY1,
(SELECT SUM(LINETOTAL) FROM ORDERDETAILS WHERE ITEMID IN 
(SELECT ID FROM ITEMS WHERE BRAND=I.BRAND AND CATEGORY1 = I.CATEGORY1)
) TOTALPRICE
FROM ITEMS I
GROUP BY I.BRAND, I.CATEGORY1
ORDER BY I.BRAND, TOTALPRICE DESC

-- Brands of each category
SELECT I.CATEGORY1, I.BRAND, SUM(OD.LINETOTAL) TOTALPRICE FROM ITEMS I
JOIN ORDERDETAILS OD ON OD.ITEMID = I.ID
GROUP BY I.CATEGORY1, I.BRAND
ORDER BY I.CATEGORY1, TOTALPRICE DESC

-- Minimum, maximum and average price of each product, how many times and units each product were sold
SELECT I.BRAND, I.CATEGORY1, I.ITEMCODE, I.ITEMNAME, 
MIN(IND.UNITPRICE) MINPRICE, MAX(IND.UNITPRICE) MAXPRICE, AVG(IND.UNITPRICE) AVGPRICE, COUNT(IND.INVOICEID) SALECOUNT, SUM(IND.AMOUNT) SALEAMOUNT
FROM INVOICEDETAILS IND
JOIN ITEMS I ON I.ID = IND.ITEMID
GROUP BY I.BRAND, I.CATEGORY1, I.ITEMCODE, I.ITEMNAME
ORDER BY I.BRAND, I.CATEGORY1

-- Number of addresses of customers and the address of the last purchase for each customer
SELECT U.NAMESURNAME,
(SELECT COUNT(*) FROM ADDRESS A WHERE U.ID = USERID) ADDRESSCOUNT,
(SELECT ADDRESSTEXT FROM ADDRESS WHERE ID IN 
(SELECT TOP 1 ADDRESSID FROM ORDERS WHERE USERID = U.ID ORDER BY DATE_ DESC) 
) LASTADDRESS
FROM USERS U

-- Number of addresses of customers and the address including the city, town and district of the last purchase.
SELECT TMP.NAMESURNAME, TMP.ADDRESSCOUNT, C.CITY, T.TOWN, D.DISTRICT, A.ADDRESSTEXT FROM
(SELECT U.NAMESURNAME,
(SELECT COUNT(*) FROM ADDRESS A WHERE U.ID = USERID) ADDRESSCOUNT,

(SELECT TOP 1 ADDRESSID FROM ORDERS WHERE USERID = U.ID ORDER BY DATE_ DESC) 
 LASTADDRESSID
FROM USERS U ) TMP

JOIN ADDRESS A ON A.ID = TMP.LASTADDRESSID
JOIN CITIES C ON C.ID = A.CITYID
JOIN TOWNS T ON T.ID = A.TOWNID
JOIN DISTRICTS D ON D.ID = A.DISTRICTID

-- Cities that recorded a daily turnover of less than 500 TL for at least 10 days in January
SELECT CITY, COUNT(*) DAYCOUNT FROM
(SELECT 
C.CITY, CONVERT(DATE, O.DATE_) DATE_, SUM(O.TOTALPRICE) TOTALPRICE FROM ORDERS O 
JOIN ADDRESS A ON A.ID = O.ADDRESSID
JOIN CITIES C ON C.ID = A.CITYID
WHERE O.DATE_ BETWEEN '20190101' AND '2019-01-31 23:59:59'
GROUP BY C.CITY, CONVERT(DATE, O.DATE_)
HAVING SUM(O.TOTALPRICE) < 500 ) TMP
GROUP BY CITY
HAVING COUNT(CITY)>=10
